In [65]:
# Import NumPy
import numpy as np
import pandas as pd

In [66]:
x= np.arange(12).reshape((3,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
x= x.reshape((6,2))
print(x)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [68]:
issubclass(x.dtype.type, np.float32)

False

In [69]:
x = (x-x.min(0))/(x.max(0) - x.min(0))
print(x)

[[0.  0. ]
 [0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.8 0.8]
 [1.  1. ]]


In [70]:
x_mean = x.mean(axis=0)
x_std = x.std(axis=0)
np.abs(np.max(x_mean)) < 12**-6
np.abs(np.max(x_std-1)) < 12**-6
print(x_mean)
print(x_std)

[0.5 0.5]
[0.34156503 0.34156503]


In [71]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
tensor = ([3, 1, 0, 2, 1])

pd.get_dummies(tensor)

0  1  2  3
0  0  0  0  1
1  0  1  0  0
2  1  0  0  0
3  0  0  1  0
4  0  1  0  0

In [73]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
np.array_equal([0,0,0,1], x[0])
np.array_equal([0,1,0,0], x[1])
np.array_equal([1,0,0,0], x[2])
np.array_equal([0,0,1,0], x[3])
np.array_equal([0,1,0,0], x[4])
x.shape == (6, 3)
print(x)

[[0.  0. ]
 [0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.8 0.8]
 [1.  1. ]]


In [79]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.datasets import load_sample_images
# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'


AttributeError: module 'numpy.linalg.lapack_lite' has no attribute '_ilp64'

In [76]:
# Load samples images
images = np.asarray(load_sample_images().images)
print(f'Number of images: {len(images)}. Images tensor: {images.shape}')

first_image = images[0]
# Display first image
plt.imshow(first_image)

# Print details about first image
print(f'First image: {first_image.shape}')

NameError: name 'load_sample_images' is not defined